name: px
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
- python=3.6
- nodejs
- cython
- cytoolz
- jupyterlab
- scikit-learn
- umap-learn
- keras
- seaborn
- flask
- flask-cors
- ipython
- pywget
- bokeh
- pydot
# We need the next line only because of a weird bug. This can probably be
# removed in the future: https://stackoverflow.com/a/52598942/981933
- testpath>=0.4.2
- pip
- pip:
  - pysam==0.13
  - hgtiles
  - cooler
  - negspy
  - pybbi
