name: px
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - python=3.7
  - nodejs=10.*
  - bwa
  - samtools
  - bedtools
  - ucsc-bedtobigbed
  - ucsc-fetchchromsizes
  - deeptools
  - cython
  - cytoolz
  - scikit-learn
  - umap-learn
  - keras==2.2.5
  - seaborn
  - flask
  - flask-cors
  - pandas
  - pywget
  - bokeh
  - pydot
  - h5py
  # We need the next line only because of a weird bug. This can probably be
  # removed in the future: https://stackoverflow.com/a/52598942/981933
  - testpath==0.4.2
  - tqdm
  - matplotlib
  - requests
  - tsfresh
  - tslearn
  - statsmodels
  - pip
  - pip:
      - apricot-select
      - cooler
      - pysam==0.15.3
      - higlass-python==0.2.1
      - ipywidgets==7.5.1
      - jupyterlab==1.1.1
      - negspy
      - numba
      - pybbi
      - keras-tqdm
      - forestci
      - fastdtw
      - stringcase
